### ISSUE TITLE
Crear .env y .env.example

### ISSUE THREAD

**Issue by Daniel-Sarmiento** [Herobrot/psicologia-nextjs#3]
ignorar solamente .env

**Comment by Daniel-Sarmiento** [comment]
ya quedó resuelto?

**Comment by Daniel-Sarmiento** [comment]
les falta el .env.example, favor de comentar las modificaciones en este mismo issue

**Comment by Herobrot** [comment]
Ya fueron arreglado

**Comment by Herobrot** [comment]
Ya fueron arreglados.
